// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// ProcessInfosDao is the data access object for table process_infos.
type ProcessInfosDao struct {
	table   string              // table is the underlying table name of the DAO.
	group   string              // group is the database configuration group name of current DAO.
	columns ProcessInfosColumns // columns contains all the column names of Table for convenient usage.
}

// ProcessInfosColumns defines and stores column names for table process_infos.
type ProcessInfosColumns struct {
	Id          string //
	ProcessName string // 流程名称
	Version     string // 流程版本
	Commnent    string // 流程备注
	DeletedAt   string //
	CreatedAt   string //
	UpdatedAt   string //
}

// processInfosColumns holds the columns for table process_infos.
var processInfosColumns = ProcessInfosColumns{
	Id:          "id",
	ProcessName: "process_name",
	Version:     "version",
	Commnent:    "commnent",
	DeletedAt:   "deleted_at",
	CreatedAt:   "created_at",
	UpdatedAt:   "updated_at",
}

// NewProcessInfosDao creates and returns a new DAO object for table data access.
func NewProcessInfosDao() *ProcessInfosDao {
	return &ProcessInfosDao{
		group:   "default",
		table:   "process_infos",
		columns: processInfosColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *ProcessInfosDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *ProcessInfosDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *ProcessInfosDao) Columns() ProcessInfosColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *ProcessInfosDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *ProcessInfosDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *ProcessInfosDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
