// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf-workflow/internal/dao/internal"
)

// internalProcessInfosDao is internal type for wrapping internal DAO implements.
type internalProcessInfosDao = *internal.ProcessInfosDao

// processInfosDao is the data access object for table process_infos.
// You can define custom methods on it to extend its functionality as you wish.
type processInfosDao struct {
	internalProcessInfosDao
}

var (
	// ProcessInfos is globally public accessible object for table process_infos operations.
	ProcessInfos = processInfosDao{
		internal.NewProcessInfosDao(),
	}
)

// Fill with you ideas below.
