// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf-workflow/internal/dao/internal"
)

// internalRolesDao is internal type for wrapping internal DAO implements.
type internalRolesDao = *internal.RolesDao

// rolesDao is the data access object for table roles.
// You can define custom methods on it to extend its functionality as you wish.
type rolesDao struct {
	internalRolesDao
}

var (
	// Roles is globally public accessible object for table roles operations.
	Roles = rolesDao{
		internal.NewRolesDao(),
	}
)

// Fill with you ideas below.
