// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf-workflow/internal/dao/internal"
)

// internalTasksDao is internal type for wrapping internal DAO implements.
type internalTasksDao = *internal.TasksDao

// tasksDao is the data access object for table tasks.
// You can define custom methods on it to extend its functionality as you wish.
type tasksDao struct {
	internalTasksDao
}

var (
	// Tasks is globally public accessible object for table tasks operations.
	Tasks = tasksDao{
		internal.NewTasksDao(),
	}
)

// Fill with you ideas below.
