// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// ProcessDefines is the golang structure for table process_defines.
type ProcessDefines struct {
	Id         uint64 `json:"id"         ` //
	ProcessId  string `json:"processId"  ` // 流程的id
	NodeName   string `json:"nodeName"   ` // 节点名称
	NextId     string `json:"nextId"     ` // 下节点id
	NextName   string `json:"nextName"   ` // 下一节点名称
	RejectId   string `json:"rejectId"   ` // 驳回节点id
	RejectName string `json:"rejectName" ` // 驳回节点名称
	Type       string `json:"type"       ` // 节点类型
	NodeInfo   string `json:"nodeInfo"   ` // 节点信息
}
