// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Tasks is the golang structure for table tasks.
type Tasks struct {
	Id                uint64      `json:"id"                ` //
	StartUserId       string      `json:"startUserId"       ` // 发起用户id
	StartUserName     string      `json:"startUserName"     ` // 发起用户名称
	NodeId            string      `json:"nodeId"            ` // 当前节点ID
	NodeName          string      `json:"nodeName"          ` // 当前节点名称
	ProcessId         string      `json:"processId"         ` // 流程ID
	ProcessName       string      `json:"processName"       ` // 流程名称
	AssigneeRoleId    string      `json:"assigneeRoleId"    ` // 应当处理该任务的角色
	AssigneeRoleName  string      `json:"assigneeRoleName"  ` // 应当处理该任务的角色
	AssigneeRoleCount int         `json:"assigneeRoleCount" ` // 表示当前任务需要多少种角色审批之后才能结束
	ActType           string      `json:"actType"           ` // 表示任务类型 "or"表示或签，即一个人通过或者驳回就结束，"and"表示会签，要所有人通过就流             转到下一步，如果有一个人驳回那么就跳转到上一步
	Conditions        string      `json:"conditions"        ` // 当前任务的条件值，由外部写入，用于流程的判断分支
	Status            string      `json:"status"            ` // 任务的状态：run、pause、finish
	DeletedAt         *gtime.Time `json:"deletedAt"         ` //
	CreatedAt         *gtime.Time `json:"createdAt"         ` //
	UpdatedAt         *gtime.Time `json:"updatedAt"         ` //
}
