// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Users is the golang structure for table users.
type Users struct {
	Id            uint64      `json:"id"            ` //
	Name          string      `json:"name"          ` //
	Password      string      `json:"password"      ` //
	RoleId        string      `json:"roleId"        ` //
	RoleName      string      `json:"roleName"      ` //
	DeletedAt     *gtime.Time `json:"deletedAt"     ` //
	RememberToken string      `json:"rememberToken" ` //
	CreatedAt     *gtime.Time `json:"createdAt"     ` //
	UpdatedAt     *gtime.Time `json:"updatedAt"     ` //
}
